sudo: false
language: rust

jobs:
  include:
    - os: linux
      rust: 1.30.0
    - os: linux
      rust: nightly
    - os: linux
      rust: beta
    - os: osx
      rust: stable
    - os: windows
      rust: stable
