[package]
name = "rand_regex"
version = "0.11.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Generates random strings and byte strings matching a regex"

[dependencies]
rand = "0.5"
regex-syntax = "0.6"

[dev-dependencies]
regex = "1.0"
